server {
  listen 80;

  location /webapp {
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    try_files $uri $uri/ /webapp/index.html =404;
  }

  location /webapp/static/ {
    root /usr/share/nginx/html;
  }

}
