spring.application.name=Task manager - Backend API
server.servlet.context-path=/api

app.cors.allowed-origins=http://localhost:3000,http://localhost:8080

app.users[0].username=testuser
app.users[0].password=password123
app.users[0].firstName=Tester
app.users[0].lastName=tests
app.users[0].roles=USER

app.users[1].username=johndoe
app.users[1].password=password123
app.users[1].firstName=John
app.users[1].lastName=Doe
app.users[1].roles=USER
