spring.application.name=Task manager - Backend API
server.servlet.context-path=/api

app.cors.allowed-origins=http://localhost:3000

app.users[0].username=testuser
app.users[0].password=password123
app.users[0].firstName=Tester
app.users[0].lastName=tests
app.users[0].roles=USER

app.users[1].username=johndoe
app.users[1].password=password123
app.users[1].firstName=John
app.users[1].lastName=Doe
app.users[1].roles=USER

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.h2.console.enabled=true
#spring.sql.init.platform=h2
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath*:/db/init/schema/*
#spring.sql.init.data-locations=classpath*:/db/init/data/*
